server:
  port: 8083
logging:
  level:
    root: INFO
    com.jkhh.provider.mapper: DEBUG


spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @env@

mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    - classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.fengzijk.blog.pojo.entity
  global-config:
    # 逻辑删除配置
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl